### ISSUE TITLE
Run Oracles and Followers paper code

### ISSUE THREAD

**Issue by nilscrm** [nilscrm/stackelberg-ml#1]
Clone the oracles and followers [github repo](https://github.com/mgerstgrasser/oracles_and_followers). Then setup a python environment carefully with the exact python and package versions mentioned in the README. Note that the first command in "Running Experiments" does not work, just use the second to try it out.

**Comment by nilscrm** [comment]
I already got the code running, so you can ask me if you struggle with the setup. I still have to get CUDA set up so it does not take ages. I also don't know yet how to view the results. I saw Weights and Biases setup in the code so maybe that's how you view the results.

**Comment by YanickZengaffinen** [comment]
Once you started the runs, ray will create folders for each job. You can cd to one of them, simply run `tensorboard --logdir=.` and then open it up in your browser.

Do think it might make sense to set it up with wandb for the final runs (especially if we move to a cluster)

**Comment by nilscrm** [comment]
Thanks.

Well depends on how much work that is. You might even need a (potentially paid idk) account on wandb and we probably have more urgent things to do till the milestone :sweat_smile:
