### ISSUE TITLE
Make new environment for oracles and follower code

### ISSUE THREAD

**Issue by nilscrm** [nilscrm/stackelberg-ml#2]
We can create a very simple other game to see that the algorithm works on our own environments.

I'm not sure though we actually need to do this. It might be fine to do just [this](https://github.com/nilscrm/stackelberg-ml/issues/4) instead.

**Comment by YanickZengaffinen** [comment]
I think making a new environment will not significantly help us bc the biggest adaptation we have to do is to go from a scenario of two agents (characterized by their policies) to a scenario where we have one RL agent (policy) and one world model (parameterized NN predicting probability of ending up in state given a state and action). Therefore, we won't be able to use the code directly anyway :/

In terms of understanding the code: probably better to look at some rllib tutorial
