### ISSUE TITLE
Adapt simple MDP to use the oracles and followers algorithms for model based RL

### ISSUE THREAD

**Issue by nilscrm** [nilscrm/stackelberg-ml#4]
After [making a simple MDP enviroment](https://github.com/nilscrm/stackelberg-ml/issues/3) we can try to instead of using the inner-outer-loop algorithms use the follower oracle. For that we need to decide, which of actor and model is the follower or leader (or try both) and then we need to come up with a way to query the leader policy.

**Comment by YanickZengaffinen** [comment]
Maybe we can consider the complexity of the conditioning of the query oracle when deciding if the actor or model should be leader/follower. E.g. if it's easier to pretrain the actor => should choose it as follower.

Long term (for report), I'd definitely try both ways though

**Comment by YanickZengaffinen** [comment]
### PAL
Model is pretrained on all policies => transitions are not affected by policy
Therefore, we wouldn't benefit at all in this case bc the model would have to learn to be good for each policy

### MAL
Policy is pretrained on all models

**Comment by YanickZengaffinen** [comment]
Will do MAL first =>

policy will be trained conditioned on world model, then world model is trained with instant best responding policy model

should probably not learn the reward function at the start (because if so, the policy has to be conditioned not only on all state-action pairs but also the state-action-state triplets from the reward)

**Comment by YanickZengaffinen** [comment]
Changed simple MDP to 
![image](https://github.com/nilscrm/stackelberg-ml/assets/42324758/6a69ed99-6e81-4a87-bd9a-9222e44b8499)

**Comment by YanickZengaffinen** [comment]
Managed to train on MDP 2, did not manage to learn model though => need to let leader see the query results (otherwise it never explores state A if poorly initialized [will always only look at B])
